export interface BillTemplateProps {
    uid: string,
    bill: number,
    date: string,
    name: string,
    phone: string,
    driver: string,
    carId: string,
    pickup: string,
    drop: string,
    startKm: number,
    endKm: number,
    price: number,
    toll: number,
    parking: number,
    days: number,
    overtime: number,
    food: number,
    advance: number,
    amount: number,
} 